version: '3'

services:
  redis:
    image: redis
    command: redis-server --requirepass ${REDIS_PASSWORD}
    ports:
      - "6379:6379"
  
  datagen:
    build:
      context: ./data_gen/
    command: python /opt/data_gen/gen_fake_data.py
    volumes:
      - ./data_gen:/opt/data_gen
    container_name: datagen
    restart: on-failure
    environment:
      PROJECT_ID: ${PROJECT_ID}
      REDIS_PASSWORD: ${REDIS_PASSWORD}
    depends_on:
      - redis
  
  streaming:
    build:
      context: ./streaming/
    command: python /opt/streaming/streaming.py --runner DirectRunner  --clicks_input_subscription=${CLICKS_INPUT_SUBSCRIPTION} --checkout_input_subscription=${CHECKOUT_INPUT_SUBSCRIPTION}
    volumes:
      - ./streaming:/opt/streaming
    container_name: streaming
    restart: on-failure
    environment:
      PROJECT_ID: ${PROJECT_ID}
      REDIS_PASSWORD: ${REDIS_PASSWORD}
      BIGQUERY_TABLE: ${BIGQUERY_TABLE}
      GOOGLE_APPLICATION_CREDENTIALS: '/opt/streaming/sa.json'
    depends_on:
      - redis