version: '3'

services:
  redis:
    image: redis
    command: redis-server --requirepass ${REDIS_PASSWORD}
    ports:
      - "6379:6379"
  
  datagen:
    build:
      context: ./data_gen/
    command: python /opt/data_gen/gen_fake_data.py
    volumes:
      - ./data_gen:/opt/data_gen
    container_name: datagen
    restart: on-failure
    environment:
      PROJECT_ID: ${PROJECT_ID}
      REDIS_PASSWORD: ${REDIS_PASSWORD}
    depends_on:
      - redis
  
  streaming:
    build:
      context: ./streaming/
    command: python -m /opt/streaming/streaming --runner DirectRunner  --clicks_input_subscription=projects/edc-igti-325912/subscriptions/clicks-sub --checkout_input_subscription=projects/edc-igti-325912/subscriptions/checkouts
    volumes:
      - ./streaming:/opt/streaming
    container_name: streaming
    restart: on-failure
    environment:
      PROJECT_ID: ${PROJECT_ID}
      REDIS_PASSWORD: ${REDIS_PASSWORD}
    depends_on:
      - redis